---
- name: Instalar Python nos nós
  hosts: localhost
  become: yes
  tasks:
    - name: Desabilitar repositório do VirtualBox
      copy:
        content: "# Desabilitado temporariamente\n"
        dest: /etc/apt/sources.list.d/virtualbox.list
      ignore_errors: yes
      when: ansible_distribution_release == "jammy"   # Se você estiver usando o Ubuntu 22.04 Jammy

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar pacotes Python alternativos
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python2-minimal:i386
        - python2-minimal
        - python-is-python3

- name: Executar tarefa no nó control-plane
  hosts: localhost
  tasks:
    - name: Atualizar pacotes no nó control-plane
      docker_container:
        name: lab-control-plane
        command: apt update && apt upgrade -y
      connection: docker

- name: Executar tarefa no nó worker
  hosts: localhost
  tasks:
    - name: Atualizar pacotes no nó worker
      docker_container:
        name: lab-worker
        command: apt update && apt upgrade -y
      connection: docker

- name: Executar tarefa no nó worker2
  hosts: localhost
  tasks:
    - name: Atualizar pacotes no nó worker2
      docker_container:
        name: lab-worker2
        command: apt update && apt upgrade -y
      connection: docker
...
